name: Snapdragon-EDK2-Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.device }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        device:
          # sm8150
          - vayu-huaxing
          - vayu-tianma
          # sm7125
          - miatoll-huaxing
          - miatoll-tianma

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y build-essential uuid-dev iasl git nasm python-is-python3 \
          gettext gcc-aarch64-linux-gnu clang llvm device-tree-compiler wine

      - name: Execute build script
        run: |
          chmod +x build.sh
          ./build.sh --device ${{ matrix.device }} --release RELEASE --installer-zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UEFI-Output-${{ matrix.device }}
          path: |
            *.zip
            *.img
          if-no-files-found: warn
